# 线性代数代码实现

In [1]:
import torch

注意：对于一维向量，虽然在pytorch中的展示形式是行向量，但按照数学意义理解应该是列向量。

## 1 标量、向量、矩阵、张量

In [2]:
# 标量：只有一个元素的张量
x = torch.tensor([3])
y = torch.tensor([2])

x+y, x-y, x*y, x/y, x**y

(tensor([5]), tensor([1]), tensor([6]), tensor([1.5000]), tensor([9]))

In [3]:
# 向量：标量组成的列表
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [4]:
# 索引——访问向量的元素
x[2]

tensor(2)

In [5]:
# 长度、形状
len(x), x.shape

(4, torch.Size([4]))

In [6]:
# 创建一个 5x4 的矩阵
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
# 转置
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

对称矩阵 `A.T = A`

In [8]:
B = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
B.T == B

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

向量是标量的推广，矩阵是向量的推广，由此，我们可以构建出更高维度的东西：

In [9]:
X = torch.arange(24.0).reshape(2,3,4)
X
# 第一个元素前面有几个 [ , 就是几维的张量
# 理解时，我们从后向前看，最后一个是列数，倒数第二个是行数，倒数第三个是矩阵数

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]],

        [[12., 13., 14., 15.],
         [16., 17., 18., 19.],
         [20., 21., 22., 23.]]])

## 2 简单运算

In [10]:
# 形状一样的矩阵可以相加
A = torch.arange(20).reshape(5,4)
B = A.clone() # 和numpy的 A.copy() 一样，B存在新的内存地址里
A, A+B

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22],
         [24, 26, 28, 30],
         [32, 34, 36, 38]]))

In [11]:
# 矩阵的元素乘法 —— 哈达玛积
# 即对应元素的简单相乘，不是线性代数里的矩阵乘法
A * B

tensor([[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121],
        [144, 169, 196, 225],
        [256, 289, 324, 361]])

In [12]:
# 标量的自动扩充
a = 2
X = torch.arange(24.0).reshape(4,6)
X, a + X

(tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10., 11.],
         [12., 13., 14., 15., 16., 17.],
         [18., 19., 20., 21., 22., 23.]]),
 tensor([[ 2.,  3.,  4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11., 12., 13.],
         [14., 15., 16., 17., 18., 19.],
         [20., 21., 22., 23., 24., 25.]]))

In [13]:
a * X, (a * X).shape

(tensor([[ 0.,  2.,  4.,  6.,  8., 10.],
         [12., 14., 16., 18., 20., 22.],
         [24., 26., 28., 30., 32., 34.],
         [36., 38., 40., 42., 44., 46.]]),
 torch.Size([4, 6]))

In [14]:
# 所有元素求和
X.sum()

tensor(276.)

In [15]:
# 求均值
X.mean(), X.sum() / X.numel() # 注意，mean() 函数仅对 浮点数 或 复数 有效

(tensor(11.5000), tensor(11.5000))

###  补充：沿轴求和

In [16]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [17]:
A_sum_axis0 = A.sum(axis=0) # axis = 0，即消去shape中第0个元素，A的shape为（5，4），消去后shape为4
A_sum_axis0, A_sum_axis0.shape

(tensor([40, 45, 50, 55]), torch.Size([4]))

In [18]:
A_sum_axis1 = A.sum(axis=1) # 同理，axis=1，shape变成（5）
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6, 22, 38, 54, 70]), torch.Size([5]))

或者，可以这么理解axis：axis=0，对应shape倒数第一个，所以按列求和，其余类似

In [19]:
A.sum(axis=[0, 1]) == A.sum() # 所有轴求和，等价于 A.sum()

tensor(True)

In [21]:
(1.0*A).mean(axis=0),A.shape[0], A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), 5, tensor([ 8.,  9., 10., 11.]))

可以发现，之前的求和、均值等操作均进行了降维（2 -> 1），但是如果我们需要广播机制，则需要保持维度一样

In [22]:
sum_A = A.sum(axis=1, keepdims=True) # 此时axis会保留dim而不会消除，dim对应的shape为1
sum_A 

tensor([[ 6],
        [22],
        [38],
        [54],
        [70]])

In [23]:
# 此时 A: 5x4 sum_A： 5x1，二者维度一样，可以利用广播机制
A / sum_A  # 归一化操作，每行的和为1

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [24]:
A.cumsum(axis=0) # 按列累加

tensor([[ 0,  1,  2,  3],
        [ 4,  6,  8, 10],
        [12, 15, 18, 21],
        [24, 28, 32, 36],
        [40, 45, 50, 55]])

## 3 乘积

### 3.1 向量 x 向量

In [26]:
# 点积, 乘出来是一个标量
x = torch.tensor([0.0,1.0,2.0,3.0])
y = torch.ones(4)
x,y, torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [27]:
# 等价于
torch.sum(x*y)

tensor(6.)

### 3.2 向量 x 矩阵

In [28]:
x = torch.tensor([1,2,3,4]) # 4x1 的列向量 
A = torch.arange(20).reshape(5,4) # 5x4 的矩阵
x,A

(tensor([1, 2, 3, 4]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]))

In [29]:
# 矩阵乘法 Ax
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 20,  60, 100, 140, 180]))

### 3.3 矩阵 x 矩阵

In [30]:
A = torch.arange(20).reshape(5,4) # 5x4 的矩阵
B = torch.arange(20).reshape(4,5) # 4x5 的矩阵
torch.mm(A, B)

tensor([[ 70,  76,  82,  88,  94],
        [190, 212, 234, 256, 278],
        [310, 348, 386, 424, 462],
        [430, 484, 538, 592, 646],
        [550, 620, 690, 760, 830]])

## 4 范数

In [31]:
# 二范数：长度
a = torch.tensor([3.0,-4.0])
torch.norm(a)

tensor(5.)

In [32]:
# 一范数：绝对值之和
torch.abs(a).sum()

tensor(7.)

In [33]:
# 佛罗贝尼乌斯 范数： 将矩阵拉平为向量，对其求二范数
torch.norm(torch.ones((4, 9)))

tensor(6.)